In [87]:
# ----------------------------
# ----------------------------
# On s'est servit de la dataFrame df pour notre travail avec Pandas
# Pour pySpark on a utiliser la dataFrame dfspark
# ----------------------------
# ----------------------------

import pandas as pd
import numpy as np
def get_spark_env(version, job_name, n):
    if version in ["3.1"]:
        from pyspark.sql import SparkSession
        spark = SparkSession.builder.master("local[*]").config('spark.executor.memoryOverhead.config', n).appName(job_name).getOrCreate()
        return spark
    elif version in ["1.6", "2.4"]:
        return None, None

def Print_DF(DF):
    return pd.DataFrame(DF.show(),columns=DF.columns)

def Print_DF_Rows(DF,NbRows):
    return pd.DataFrame(DF.take(NbRows),columns=DF.columns)

job_name = 'Formation'
spark = get_spark_env("3.1", job_name, '4g')
print (spark.version)

3.1.1

In [88]:
#df DataFrame Pandas
#dfspark DataFrame PySpark

import pandas as pd
# df = pd.read_csv('Dataset_11_poke.csv' , sep="|")
# df
dfspark = spark.read.csv('Dataset_11_poke.csv', header=True , sep='|')
dfspark.printSchema()

root
 |-- _c0: string (nullable = true)
 |-- Unnamed: 0: string (nullable = true)
 |-- Unnamed: 0.1: string (nullable = true)
 |-- Unnamed: 0.1.1: string (nullable = true)
 |-- Unnamed: 0.1.1.1: string (nullable = true)
 |-- Unnamed: 0.1.1.1.1: string (nullable = true)
 |-- Unnamed: 0.1.1.1.1.1: string (nullable = true)
 |-- Unnamed: 0.1.1.1.1.1.1: string (nullable = true)
 |-- Unnamed: 0.1.1.1.1.1.1.1: string (nullable = true)
 |-- Unnamed: 0.1.1.1.1.1.1.1.1: string (nullable = true)
 |-- Unnamed: 0.1.1.1.1.1.1.1.1.1: string (nullable = true)
 |-- abilities: string (nullable = true)
 |-- against_bug: string (nullable = true)
 |-- against_dark: string (nullable = true)
 |-- against_dragon: string (nullable = true)
 |-- against_electric: string (nullable = true)
 |-- against_fairy: string (nullable = true)
 |-- against_fight: string (nullable = true)
 |-- against_fire: string (nullable = true)
 |-- against_flying: string (nullable = true)
 |-- against_ghost: string (nullable = true)
 |-- against_grass: string (nullable = true)
 |-- against_ground: string (nullable = true)
 |-- against_ice: string (nullable = true)
 |-- against_normal: string (nullable = true)
 |-- against_poison: string (nullable = true)
 |-- against_psychic: string (nullable = true)
 |-- against_rock: string (nullable = true)
 |-- against_steel: string (nullable = true)
 |-- against_water: string (nullable = true)
 |-- attack: string (nullable = true)
 |-- base_egg_steps: string (nullable = true)
 |-- base_happiness: string (nullable = true)
 |-- base_total: string (nullable = true)
 |-- capture_rate: string (nullable = true)
 |-- classfication: string (nullable = true)
 |-- defense: string (nullable = true)
 |-- experience_growth: string (nullable = true)
 |-- height_m: string (nullable = true)
 |-- hp: string (nullable = true)
 |-- japanese_name: string (nullable = true)
 |-- name: string (nullable = true)
 |-- percentage_male: string (nullable = true)
 |-- pokedex_number: string (nullable = true)
 |-- sp_attack: string (nullable = true)
 |-- sp_defense: string (nullable = true)
 |-- speed: string (nullable = true)
 |-- type1: string (nullable = true)
 |-- type2: string (nullable = true)
 |-- weight_kg: string (nullable = true)
 |-- generation: string (nullable = true)
 |-- is_legendary: string (nullable = true)

In [89]:
# Supprimer les colonnes inutile
# df.drop([col for col in df.columns if 'Unnamed' in col],axis=1,inplace=True)
# df
dfspark = dfspark.drop("Unnamed: 0")
for i in  dfspark.columns:
    add=""
    name = "Unnamed: 0"
    dfspark = dfspark.drop("_c0")
    dfspark = dfspark.drop("Unnamed: 0")
    for j in i:
        add += ".1"
        dfspark = dfspark.drop(name+add)

dfspark

DataFrame[abilities: string, against_bug: string, against_dark: string, against_dragon: string, against_electric: string, against_fairy: string, against_fight: string, against_fire: string, against_flying: string, against_ghost: string, against_grass: string, against_ground: string, against_ice: string, against_normal: string, against_poison: string, against_psychic: string, against_rock: string, against_steel: string, against_water: string, attack: string, base_egg_steps: string, base_happiness: string, base_total: string, capture_rate: string, classfication: string, defense: string, experience_growth: string, height_m: string, hp: string, japanese_name: string, name: string, percentage_male: string, pokedex_number: string, sp_attack: string, sp_defense: string, speed: string, type1: string, type2: string, weight_kg: string, generation: string, is_legendary: string]

In [92]:
# Afficher des colonnes suivantes
# df.loc[:,['name','japanese_name','generation','attack']]
dfspark.select('name', 'japanese_name','generation','attack').collect()

[Row(name='Bulbasaur', japanese_name='Fushigidaneフシギダネ', generation='1', attack='49'),
 Row(name='Ivysaur', japanese_name='Fushigisouフシギソウ', generation='1', attack='62'),
 Row(name='Venusaur', japanese_name='Fushigibanaフシギバナ', generation='1', attack='100'),
 Row(name='Charmander', japanese_name='Hitokageヒトカゲ', generation='1', attack='52'),
 Row(name='Charmeleon', japanese_name='Lizardoリザード', generation='1', attack='64'),
 Row(name='Charizard', japanese_name='Lizardonリザードン', generation='1', attack='104'),
 Row(name='Squirtle', japanese_name='Zenigameゼニガメ', generation='1', attack='48'),
 Row(name='Wartortle', japanese_name='Kameilカメール', generation='1', attack='63'),
 Row(name='Blastoise', japanese_name='Kamexカメックス', generation='1', attack='103'),
 Row(name='Caterpie', japanese_name='Caterpieキャタピー', generation='1', attack='30'),
 Row(name='Metapod', japanese_name='Transelトランセル', generation='1', attack='20'),
 Row(name='Butterfree', japanese_name='Butterfreeバタフリー', generation='1', attack='45'),
 Row(name='Weedle', japanese_name='Beedleビードル', generation='1', attack='35'),
 Row(name='Kakuna', japanese_name='Cocoonコクーン', generation='1', attack='25'),
 Row(name='Beedrill', japanese_name='Spearスピアー', generation='1', attack='150'),
 Row(name='Pidgey', japanese_name='Poppoポッポ', generation='1', attack='45'),
 Row(name='Pidgeotto', japanese_name='Pigeonピジョン', generation='1', attack='60'),
 Row(name='Pidgeot', japanese_name='Pigeotピジョット', generation='1', attack='80'),
 Row(name='Rattata', japanese_name='Korattaコラッタ', generation='1', attack='56'),
 Row(name='Raticate', japanese_name='Rattaラッタ', generation='1', attack='71'),
 Row(name='Spearow', japanese_name='Onisuzumeオニスズメ', generation='1', attack='60'),
 Row(name='Fearow', japanese_name='Onidrillオニドリル', generation='1', attack='90'),
 Row(name='Ekans', japanese_name='Arboアーボ', generation='1', attack='60'),
 Row(name='Arbok', japanese_name='Arbokアーボック', generation='1', attack='95'),
 Row(name='Pikachu', japanese_name='Pikachuピカチュウ', generation='1', attack='55'),
 Row(name='Raichu', japanese_name='Raichuライチュウ', generation='1', attack='85'),
 Row(name='Sandshrew', japanese_name='Sandサンド', generation='1', attack='75'),
 Row(name='Sandslash', japanese_name='Sandpanサンドパン', generation='1', attack='100'),
 Row(name='Nidoran♀', japanese_name='Nidoran?ニドラン♀', generation='1', attack='47'),
 Row(name='Nidorina', japanese_name='Nidorinaニドリーナ', generation='1', attack='62'),
 Row(name='Nidoqueen', japanese_name='Nidoqueenニドクイン', generation='1', attack='92'),
 Row(name='Nidoran♂', japanese_name='Nidoran?ニドラン♂', generation='1', attack='57'),
 Row(name='Nidorino', japanese_name='Nidorinoニドリーノ', generation='1', attack='72'),
 Row(name='Nidoking', japanese_name='Nidokingニドキング', generation='1', attack='102'),
 Row(name='Clefairy', japanese_name='Pippiピッピ', generation='1', attack='45'),
 Row(name='Clefable', japanese_name='Pixyピクシー', generation='1', attack='70'),
 Row(name='Vulpix', japanese_name='Rokonロコン', generation='1', attack='41'),
 Row(name='Ninetales', japanese_name='Kyukonキュウコン', generation='1', attack='67'),
 Row(name='Jigglypuff', japanese_name='Purinプリン', generation='1', attack='45'),
 Row(name='Wigglytuff', japanese_name='Pukurinプクリン', generation='1', attack='70'),
 Row(name='Zubat', japanese_name='Zubatズバット', generation='1', attack='45'),
 Row(name='Golbat', japanese_name='Golbatゴルバット', generation='1', attack='80'),
 Row(name='Oddish', japanese_name='Nazonokusaナゾノクサ', generation='1', attack='50'),
 Row(name='Gloom', japanese_name='Kusaihanaクサイハナ', generation='1', attack='65'),
 Row(name='Vileplume', japanese_name='Ruffresiaラフレシア', generation='1', attack='80'),
 Row(name='Paras', japanese_name='Parasパラス', generation='1', attack='70'),
 Row(name='Parasect', japanese_name='Parasectパラセクト', generation='1', attack='95'),
 Row(name='Venonat', japanese_name='Kongpangコンパン', generation='1', attack='55'),
 Row(name='Venomoth', japanese_name='Morphonモルフォン', generation='1', attack='65'),
 Row(name='Diglett', japanese_name='Digdaディグダ', generation='1', attack='55'),
 Row(name='Dugtrio', japanese_name='Dugtrioダグトリオ', generation='1', attack='100'),
 Row(name='Meowth', japanese_name='Nyarthニャース', generation='1', attack='35'),
 Row(name='Persian', japanese_name='Persianペルシアン', generation='1', attack='60'),
 Row(name='Psyduck', japanese_name='Koduckコダック', generation='1', attack='52'),
 Row(name='Golduck', japanese_name='Golduckゴルダック', generation='1', attack='82'),
 Row(name='Mankey', japanese_name='Mankeyマンキー', generation='1', attack='80'),
 Row(name='Primeape', japanese_name='Okorizaruオコリザル', generation='1', attack='105'),
 Row(name='Growlithe', japanese_name='Gardieガーディ', generation='1', attack='70'),
 Row(name='Arcanine', japanese_name='Windieウインディ', generation='1', attack='110'),
 Row(name='Poliwag', japanese_name='Nyoromoニョロモ', generation='1', attack='50'),
 Row(name='Poliwhirl', japanese_name='Nyorozoニョロゾ', generation='1', attack='65'),
 Row(name='Poliwrath', japanese_name='Nyorobonニョロボン', generation='1', attack='95'),
 Row(name='Abra', japanese_name='Caseyケーシィ', generation='1', attack='20'),
 Row(name='Kadabra', japanese_name='Yungererユンゲラー', generation='1', attack='35'),
 Row(name='Alakazam', japanese_name='Foodinフーディン', generation='1', attack='50'),
 Row(name='Machop', japanese_name='Wanrikyワンリキー', generation='1', attack='80'),
 Row(name='Machoke', japanese_name='Gorikyゴーリキー', generation='1', attack='100'),
 Row(name='Machamp', japanese_name='Kairikyカイリキー', generation='1', attack='130'),
 Row(name='Bellsprout', japanese_name='Madatsubomiマダツボミ', generation='1', attack='75'),
 Row(name='Weepinbell', japanese_name='Utsudonウツドン', generation='1', attack='90'),
 Row(name='Victreebel', japanese_name='Utsubotウツボット', generation='1', attack='105'),
 Row(name='Tentacool', japanese_name='Menokurageメノクラゲ', generation='1', attack='40'),
 Row(name='Tentacruel', japanese_name='Dokukurageドククラゲ', generation='1', attack='70'),
 Row(name='Geodude', japanese_name='Isitsubuteイシツブテ', generation='1', attack='80'),
 Row(name='Graveler', japanese_name='Goloneゴローン', generation='1', attack='95'),
 Row(name='Golem', japanese_name='Golonyaゴローニャ', generation='1', attack='120'),
 Row(name='Ponyta', japanese_name='Ponytaポニータ', generation='1', attack='85'),
 Row(name='Rapidash', japanese_name='Gallopギャロップ', generation='1', attack='100'),
 Row(name='Slowpoke', japanese_name='Yadonヤドン', generation='1', attack='65'),
 Row(name='Slowbro', japanese_name='Yadoranヤドラン', generation='1', attack='75'),
 Row(name='Magnemite', japanese_name='Coilコイル', generation='1', attack='35'),
 Row(name='Magneton', japanese_name='Rarecoilレアコイル', generation='1', attack='60'),
 Row(name="Farfetch'd", japanese_name='Kamonegiカモネギ', generation='1', attack='90'),
 Row(name='Doduo', japanese_name='Dodoドードー', generation='1', attack='85'),
 Row(name='Dodrio', japanese_name='Dodorioドードリオ', generation='1', attack='110'),
 Row(name='Seel', japanese_name='Pawouパウワウ', generation='1', attack='45'),
 Row(name='Dewgong', japanese_name='Jugonジュゴン', generation='1', attack='70'),
 Row(name='Grimer', japanese_name='Betbeterベトベター', generation='1', attack='80'),
 Row(name='Muk', japanese_name='Betbetonベトベトン', generation='1', attack='105'),
 Row(name='Shellder', japanese_name='Shellderシェルダー', generation='1', attack='65'),
 Row(name='Cloyster', japanese_name='Parshenパルシェン', generation='1', attack='95'),
 Row(name='Gastly', japanese_name='Ghosゴース', generation='1', attack='35'),
 Row(name='Haunter', japanese_name='Ghostゴースト', generation='1', attack='50'),
 Row(name='Gengar', japanese_name='Gangarゲンガー', generation='1', attack='65'),
 Row(name='Onix', japanese_name='Iwarkイワーク', generation='1', attack='45'),
 Row(name='Drowzee', japanese_name='Sleepeスリープ', generation='1', attack='48'),
 Row(name='Hypno', japanese_name='Sleeperスリーパー', generation='1', attack='73'),
 Row(name='Krabby', japanese_name='Crabクラブ', generation='1', attack='105'),
 Row(name='Kingler', japanese_name='Kinglerキングラー', generation='1', attack='130'),
 Row(name='Voltorb', japanese_name='Biriridamaビリリダマ', generation='1', attack='30'),
 Row(name='Electrode', japanese_name='Marumineマルマイン', generation='1', attack='50'),
 Row(name='Exeggcute', japanese_name='Tamatamaタマタマ', generation='1', attack='40'),
 Row(name='Exeggutor', japanese_name='Nassyナッシー', generation='1', attack='105'),
 Row(name='Cubone', japanese_name='Karakaraカラカラ', generation='1', attack='50'),
 Row(name='Marowak', japanese_name='Garagaraガラガラ', generation='1', attack='80'),
 Row(name='Hitmonlee', japanese_name='Sawamularサワムラー', generation='1', attack='120'),
 Row(name='Hitmonchan', japanese_name='Ebiwalarエビワラー', generation='1', attack='105'),
 Row(name='Lickitung', japanese_name='Beroringaベロリンガ', generation='1', attack='55'),
 Row(name='Koffing', japanese_name='Dogarsドガース', generation='1', attack='65'),
 Row(name='Weezing', japanese_name='Matadogasマタドガス', generation='1', attack='90'),
 Row(name='Rhyhorn', japanese_name='Sihornサイホーン', generation='1', attack='85'),
 Row(name='Rhydon', japanese_name='Sidonサイドン', generation='1', attack='130'),
 Row(name='Chansey', japanese_name='Luckyラッキー', generation='1', attack='5'),
 Row(name='Tangela', japanese_name='Monjaraモンジャラ', generation='1', attack='55'),
 Row(name='Kangaskhan', japanese_name='Garuraガルーラ', generation='1', attack='125'),
 Row(name='Horsea', japanese_name='Tattuタッツー', generation='1', attack='40'),
 Row(name='Seadra', japanese_name='Seadraシードラ', generation='1', attack='65'),
 Row(name='Goldeen', japanese_name='Tosakintoトサキント', generation='1', attack='67'),
 Row(name='Seaking', japanese_name='Azumaoアズマオウ', generation='1', attack='92'),
 Row(name='Staryu', japanese_name='Hitodemanヒトデマン', generation='1', attack='45'),
 Row(name='Starmie', japanese_name='Starmieスターミー', generation='1', attack='75'),
 Row(name='Mr. Mime', japanese_name='Barrierdバリヤード', generation='1', attack='45'),
 Row(name='Scyther', japanese_name='Strikeストライク', generation='1', attack='110'),
 Row(name='Jynx', japanese_name='Rougelaルージュラ', generation='1', attack='50'),
 Row(name='Electabuzz', japanese_name='Elebooエレブー', generation='1', attack='83'),
 Row(name='Magmar', japanese_name='Booberブーバー', generation='1', attack='95'),
 Row(name='Pinsir', japanese_name='Kailiosカイロス', generation='1', attack='155'),
 Row(name='Tauros', japanese_name='Kentaurosケンタロス', generation='1', attack='100'),
 Row(name='Magikarp', japanese_name='Koikingコイキング', generation='1', attack='10'),
 Row(name='Gyarados', japanese_name='Gyaradosギャラドス', generation='1', attack='155'),
 Row(name='Lapras', japanese_name='Laplaceラプラス', generation='1', attack='85'),
 Row(name='Ditto', japanese_name='Metamonメタモン', generation='1', attack='48'),
 Row(name='Eevee', japanese_name='Eievuiイーブイ', generation='1', attack='55'),
 Row(name='Vaporeon', japanese_name='Showersシャワーズ', generation='1', attack='65'),
 Row(name='Jolteon', japanese_name='Thundersサンダース', generation='1', attack='65'),
 Row(name='Flareon', japanese_name='Boosterブースター', generation='1', attack='130'),
 Row(name='Porygon', japanese_name='Porygonポリゴン', generation='1', attack='60'),
 Row(name='Omanyte', japanese_name='Omniteオムナイト', generation='1', attack='40'),
 Row(name='Omastar', japanese_name='Omstarオムスター', generation='1', attack='60'),
 Row(name='Kabuto', japanese_name='Kabutoカブト', generation='1', attack='80'),
 Row(name='Kabutops', japanese_name='Kabutopsカブトプス', generation='1', attack='115'),
 Row(name='Aerodactyl', japanese_name='Pteraプテラ', generation='1', attack='135'),
 Row(name='Snorlax', japanese_name='Kabigonカビゴン', generation='1', attack='110'),
 Row(name='Articuno', japanese_name='Freezerフリーザー', generation='1', attack='85'),
 Row(name='Zapdos', japanese_name='Thunderサンダー', generation='1', attack='90'),
 Row(name='Moltres', japanese_name='Fireファイヤー', generation='1', attack='100'),
 Row(name='Dratini', japanese_name='Miniryuミニリュウ', generation='1', attack='64'),
 Row(name='Dragonair', japanese_name='Hakuryuハクリュー', generation='1', attack='84'),
 Row(name='Dragonite', japanese_name='Kairyuカイリュー', generation='1', attack='134'),
 Row(name='Mewtwo', japanese_name='Mewtwoミュウツー', generation='1', attack='150'),
 Row(name='Mew', japanese_name='Mewミュウ', generation='1', attack='100'),
 Row(name='Chikorita', japanese_name='Chicoritaチコリータ', generation='2', attack='49'),
 Row(name='Bayleef', japanese_name='Bayleafベイリーフ', generation='2', attack='62'),
 Row(name='Meganium', japanese_name='Meganiumメガニウム', generation='2', attack='82'),
 Row(name='Cyndaquil', japanese_name='Hinoarashiヒノアラシ', generation='2', attack='52'),
 Row(name='Quilava', japanese_name='Magmarashiマグマラシ', generation='2', attack='64'),
 Row(name='Typhlosion', japanese_name='Bakphoonバクフーン', generation='2', attack='84'),
 Row(name='Totodile', japanese_name='Waninokoワニノコ', generation='2', attack='65'),
 Row(name='Croconaw', japanese_name='Alligatesアリゲイツ', generation='2', attack='80'),
 Row(name='Feraligatr', japanese_name='Ordileオーダイル', generation='2', attack='105'),
 Row(name='Sentret', japanese_name='Otachiオタチ', generation='2', attack='46'),
 Row(name='Furret', japanese_name='Ootachiオオタチ', generation='2', attack='76'),
 Row(name='Hoothoot', japanese_name='Hohoホーホー', generation='2', attack='30'),
 Row(name='Noctowl', japanese_name='Yorunozukuヨルノズク', generation='2', attack='50'),
 Row(name='Ledyba', japanese_name='Redibaレディバ', generation='2', attack='20'),
 Row(name='Ledian', japanese_name='Redianレディアン', generation='2', attack='35'),
 Row(name='Spinarak', japanese_name='Itomaruイトマル', generation='2', attack='60'),
 Row(name='Ariados', japanese_name='Ariadosアリアドス', generation='2', attack='90'),
 Row(name='Crobat', japanese_name='Crobatクロバット', generation='2', attack='90'),
 Row(name='Chinchou', japanese_name='Chonchieチョンチー', generation='2', attack='38'),
 Row(name='Lanturn', japanese_name='Lanternランターン', generation='2', attack='58'),
 Row(name='Pichu', japanese_name='Pichuピチュー', generation='2', attack='40'),
 Row(name='Cleffa', japanese_name='Pyピィ', generation='2', attack='25'),
 Row(name='Igglybuff', japanese_name='Pupurinププリン', generation='2', attack='30'),
 Row(name='Togepi', japanese_name='Togepyトゲピー', generation='2', attack='20'),
 Row(name='Togetic', japanese_name='Togechickトゲチック', generation='2', attack='40'),
 Row(name='Natu', japanese_name='Natyネイティ', generation='2', attack='50'),
 Row(name='Xatu', japanese_name='Natioネイティオ', generation='2', attack='75'),
 Row(name='Mareep', japanese_name='Merriepメリープ', generation='2', attack='40'),
 Row(name='Flaaffy', japanese_name='Mokokoモココ', generation='2', attack='55'),
 Row(name='Ampharos', japanese_name='Denryuデンリュウ', generation='2', attack='95'),
 Row(name='Bellossom', japanese_name='Kireihanaキレイハナ', generation='2', attack='80'),
 Row(name='Marill', japanese_name='Marilマリル', generation='2', attack='20'),
 Row(name='Azumarill', japanese_name='Marilliマリルリ', generation='2', attack='50'),
 Row(name='Sudowoodo', japanese_name='Usokkieウソッキー', generation='2', attack='100'),
 Row(name='Politoed', japanese_name='Nyorotonoニョロトノ', generation='2', attack='75'),
 Row(name='Hoppip', japanese_name='Haneccoハネッコ', generation='2', attack='35'),
 Row(name='Skiploom', japanese_name='Popoccoポポッコ', generation='2', attack='45'),
 Row(name='Jumpluff', japanese_name='Wataccoワタッコ', generation='2', attack='55'),
 Row(name='Aipom', japanese_name='Eipamエイパム', generation='2', attack='70'),
 Row(name='Sunkern', japanese_name='Himanutsヒマナッツ', generation='2', attack='30'),
 Row(name='Sunflora', japanese_name='Kimawariキマワリ', generation='2', attack='75'),
 Row(name='Yanma', japanese_name='Yanyanmaヤンヤンマ', generation='2', attack='65'),
 Row(name='Wooper', japanese_name='Upahウパー', generation='2', attack='45'),
 Row(name='Quagsire', japanese_name='Nuohヌオー', generation='2', attack='85'),
 Row(name='Espeon', japanese_name='Eifieエーフィ', generation='2', attack='65'),
 Row(name='Umbreon', japanese_name='Blackyブラッキー', generation='2', attack='65'),
 Row(name='Murkrow', japanese_name='Yamikarasuヤミカラス', generation='2', attack='85'),
 Row(name='Slowking', japanese_name='Yadokingヤドキング', generation='2', attack='75'),
 Row(name='Misdreavus', japanese_name='Mumaムウマ', generation='2', attack='60'),
 Row(name='Unown', japanese_name='Unknownアンノーン', generation='2', attack='72'),
 Row(name='Wobbuffet', japanese_name='Sonansソーナンス', generation='2', attack='33'),
 Row(name='Girafarig', japanese_name='Kirinrikiキリンリキ', generation='2', attack='80'),
 Row(name='Pineco', japanese_name='Kunugidamaクヌギダマ', generation='2', attack='65'),
 Row(name='Forretress', japanese_name='Foretosフォレトス', generation='2', attack='90'),
 Row(name='Dunsparce', japanese_name='Nokocchiノコッチ', generation='2', attack='70'),
 Row(name='Gligar', japanese_name='Gligerグライガー', generation='2', attack='75'),
 Row(name='Steelix', japanese_name='Haganeilハガネール', generation='2', attack='125'),
 Row(name='Snubbull', japanese_name='Buluブルー', generation='2', attack='80'),
 Row(name='Granbull', japanese_name='Granbuluグランブル', generation='2', attack='120'),
 Row(name='Qwilfish', japanese_name='Harysenハリーセン', generation='2', attack='95'),
 Row(name='Scizor', japanese_name='Hassamハッサム', generation='2', attack='150'),
 Row(name='Shuckle', japanese_name='Tsubotsuboツボツボ', generation='2', attack='10'),
 Row(name='Heracross', japanese_name='Heracrosヘラクロス', generation='2', attack='185'),
 Row(name='Sneasel', japanese_name='Nyulaニューラ', generation='2', attack='95'),
 Row(name='Teddiursa', japanese_name='Himegumaヒメグマ', generation='2', attack='80'),
 Row(name='Ursaring', japanese_name='Ringumaリングマ', generation='2', attack='130'),
 Row(name='Slugma', japanese_name='Magmagマグマッグ', generation='2', attack='40'),
 Row(name='Magcargo', japanese_name='Magcargotマグカルゴ', generation='2', attack='50'),
 Row(name='Swinub', japanese_name='Urimooウリムー', generation='2', attack='50'),
 Row(name='Piloswine', japanese_name='Inomooイノムー', generation='2', attack='100'),
 Row(name='Corsola', japanese_name='Sunnygoサニーゴ', generation='2', attack='55'),
 Row(name='Remoraid', japanese_name='Teppouoテッポウオ', generation='2', attack='65'),
 Row(name='Octillery', japanese_name='Okutankオクタン', generation='2', attack='105'),
 Row(name='Delibird', japanese_name='Delibirdデリバード', generation='2', attack='55'),
 Row(name='Mantine', japanese_name='Mantainマンタイン', generation='2', attack='40'),
 Row(name='Skarmory', japanese_name='Airmdエアームド', generation='2', attack='80'),
 Row(name='Houndour', japanese_name='Delvilデルビル', generation='2', attack='60'),
 Row(name='Houndoom', japanese_name='Hellgarヘルガー', generation='2', attack='90'),
 Row(name='Kingdra', japanese_name='Kingdraキングドラ', generation='2', attack='95'),
 Row(name='Phanpy', japanese_name='Gomazouゴマゾウ', generation='2', attack='60'),
 Row(name='Donphan', japanese_name='Donfanドンファン', generation='2', attack='120'),
 Row(name='Porygon2', japanese_name='Porygon2ポリゴン２', generation='2', attack='80'),
 Row(name='Stantler', japanese_name='Odoshishiオドシシ', generation='2', attack='95'),
 Row(name='Smeargle', japanese_name='Dobleドーブル', generation='2', attack='20'),
 Row(name='Tyrogue', japanese_name='Balkieバルキー', generation='2', attack='35'),
 Row(name='Hitmontop', japanese_name='Kapoererカポエラー', generation='2', attack='95'),
 Row(name='Smoochum', japanese_name='Muchulムチュール', generation='2', attack='30'),
 Row(name='Elekid', japanese_name='Elekidエレキッド', generation='2', attack='63'),
 Row(name='Magby', japanese_name='Bubyブビィ', generation='2', attack='75'),
 Row(name='Miltank', japanese_name='Miltankミルタンク', generation='2', attack='80'),
 Row(name='Blissey', japanese_name='Happinasハピナス', generation='2', attack='10'),
 Row(name='Raikou', japanese_name='Raikouライコウ', generation='2', attack='85'),
 Row(name='Entei', japanese_name='Enteiエンテイ', generation='2', attack='115'),
 Row(name='Suicune', japanese_name='Suicuneスイクン', generation='2', attack='75'),
 Row(name='Larvitar', japanese_name='Yogirasヨーギラス', generation='2', attack='64'),
 Row(name='Pupitar', japanese_name='Sanagirasサナギラス', generation='2', attack='84'),

In [77]:
df.sort_values(by='attack', ascending=False).loc[:,["name","generation", "attack"]]

          name  generation  attack
213  Heracross           2     185
797    Kartana           7     181
382    Groudon           3     180
383   Rayquaza           3     180
444   Garchomp           4     170
..         ...         ...     ...
241    Blissey           2      10
128   Magikarp           1      10
212    Shuckle           2      10
439    Happiny           4       5
112    Chansey           1       5

[801 rows x 3 columns]

In [78]:
# df.describe()
dfspark.describe().show()

+-------+-----------+------------------+------------------+-------------------+------------------+------------------+------------------+------------------+------------------+------------------+-----------------+------------------+------------------+------------------+------------------+-------------------+------------------+------------------+------------------+-----------------+-----------------+------------------+------------------+-----------------+-----------------+------------------+------------------+------------------+------------------+--------------------+---------+------------------+-----------------+-----------------+------------------+------------------+-----+-----+------------------+-----------------+-------------------+
|summary|  abilities|       against_bug|      against_dark|     against_dragon|  against_electric|     against_fairy|     against_fight|      against_fire|    against_flying|     against_ghost|    against_grass|    against_ground|       against_ice|    against_normal|    against_poison|    against_psychic|      against_rock|     against_steel|     against_water|           attack|   base_egg_steps|    base_happiness|        base_total|     capture_rate|    classfication|           defense| experience_growth|          height_m|                hp|       japanese_name|     name|   percentage_male|   pokedex_number|        sp_attack|        sp_defense|             speed|type1|type2|         weight_kg|       generation|       is_legendary|
+-------+-----------+------------------+------------------+-------------------+------------------+------------------+------------------+------------------+------------------+------------------+-----------------+------------------+------------------+------------------+------------------+-------------------+------------------+------------------+------------------+-----------------+-----------------+------------------+------------------+-----------------+-----------------+------------------+------------------+------------------+------------------+--------------------+---------+------------------+-----------------+-----------------+------------------+------------------+-----+-----+------------------+-----------------+-------------------+
|  count|        801|               786|               786|                801|               751|               706|               801|               801|               751|               801|              801|               801|               801|               801|               801|                801|               801|               801|               801|              801|              801|               801|               801|              801|              801|               801|               801|               781|               801|                 801|      801|               703|              801|              801|               801|               801|  801|  417|               781|              801|                801|
|   mean|        0.0|0.9975795297372061|1.0568350668647846|-5.8746438746438745|1.0753968253968254|1.0513117283950617|1.0662450066577895|1.1474700399467377|1.1957390146471372|0.9820239680426098|1.034019975031211|1.0980024968789013|1.2081772784019975|0.8870162297128589|0.9753433208489388| 1.0053058676654183|1.2503121098626717| 0.983458177278402|1.0583645443196006|77.85767790262172|7191.011235955056| 65.36204744069913| 428.3770287141074|         98.76125|             null| 73.00873907615481|1054995.9051186019| 1.163892445582586| 68.95880149812734|                null|     null|55.155761024181935|            401.0|71.30586766541823| 70.91136079900124| 66.33458177278402| null| null| 61.37810499359791|3.690387016229713|0.08739076154806492|
| stddev|        0.0|0.6093207973147001| 0.441122011473674| 52.013968120953294|0.6661977087169648|0.5007434735698707| 0.719274459362836|0.7001001767136843|0.6116658835746529|0.5525785899683715|0.788895949793443|0.7388181474447942|0.7353561542090227|0.2661061085098709|0.5493752481077555|0.49518298393424987|0.6971481388239287|0.5001166374568771|0.6065619893640909|32.15882023801748|6558.220421815937|19.598947874892335|119.20357658921323|76.25782463596947|             null|30.769159454445337|160255.83509567135|1.0803262606466888|26.576014572576504|                null|     null|20.261622677255126|231.3730753566629|32.35382632746033|27.942501378203644|28.907661875463337| null| null|109.35476585346383|1.930419637030045| 0.2825832768663855|
|    min|          0|              0.25|              0.25|             -400.0|               0.0|              0.25|               0.0|              0.25|              0.25|               0.0|             0.25|               0.0|              0.25|               0.0|               0.0|                0.0|              0.25|              0.25|              0.25|               10|            10240|                 0|               180|              100|Abundance Pokémon|                10|           1000000|               0.1|                 1|  Abagouraアバゴーラ|Abomasnow|               0.0|                1|               10|               100|                10|  bug|  bug|               0.1|                1|                  0|
|    max|ù*ùfsfsf///|             hello|       ù*ùfsfsf///|              hello|       ù*ùfsfsf///|              None|       ù*ùfsfsf///|       ù*ùfsfsf///|               4.0|             hello|              4.0|               4.0|               4.0|               1.0|               4.0|                4.0|               4.0|               4.0|               4.0|               98|             8960|                90|               780|               90|Zen Charm Pokémon|                99|            800000|               9.2|                99|Zygarde (10% Form...|  Zygarde|              88.1|               99|               99|                99|                99|water|water|             999.9|                7|                  1|
+-------+-----------+------------------+------------------+-------------------+------------------+------------------+------------------+------------------+------------------+------------------+-----------------+------------------+------------------+------------------+------------------+-------------------+------------------+------------------+------------------+-----------------+-----------------+------------------+------------------+-----------------+-----------------+------------------+------------------+------------------+------------------+--------------------+---------+------------------+-----------------+-----------------+------------------+------------------+-----+-----+------------------+-----------------+-------------------+

In [121]:
# Moyenne des pourcentages
# df['percentage_male'] = df['percentage_male'].fillna(df['percentage_male'].mean())
# df['percentage_male']
dfspark.filter(dfspark['percentage_male'] < 100000).agg({"percentage_male": "avg"}).show()

+--------------------+
|avg(percentage_male)|
+--------------------+
|  55.155761024181935|
+--------------------+

In [81]:
# Voir les 51 premières valeurs 
# df.loc[:50]

Print_DF_Rows(dfspark,10)

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,Allez au boulot ! :),1.0,1.0,hello,None,None,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,hello,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,ù*ùfsfsf///,1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,None,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,None,1.0,1.0,0.5,ù*ùfsfsf///,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,None,19.0,1,0
5,"['Blaze', 'Solar Power']",0.25,1.0,-400.0,2.0,0.5,0.5,0.5,1.0,1.0,...,88.1,6,159,115,100,fire,flying,90.5,1,0
6,"['Torrent', 'Rain Dish']",hello,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,7,50,64,43,water,None,9.0,1,0
7,"['Torrent', 'Rain Dish']",1.0,1.0,1.0,2.0,None,1.0,0.5,1.0,1.0,...,88.1,8,65,80,58,water,None,22.5,1,0
8,"['Torrent', 'Rain Dish']",1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,9,135,115,78,water,None,85.5,1,0
9,"['Shield Dust', 'Run Away']",1.0,None,1.0,1.0,None,0.5,2.0,2.0,1.0,...,50.0,10,20,20,45,bug,None,2.9,1,0

In [9]:
# Affiche le nombre de valeurs manquantes par valeurs
for x in df:
    print(x ,df[df[x].isnull()].shape[0])

abilities 0
against_bug 15
against_dark 15
against_dragon 0
against_electric 50
against_fairy 95
against_fight 0
against_fire 0
against_flying 50
against_ghost 0
against_grass 0
against_ground 0
against_ice 0
against_normal 0
against_poison 0
against_psychic 0
against_rock 0
against_steel 0
against_water 0
attack 0
base_egg_steps 0
base_happiness 0
base_total 0
capture_rate 0
classfication 0
defense 0
experience_growth 0
height_m 20
hp 0
japanese_name 0
name 0
percentage_male 0
pokedex_number 0
sp_attack 0
sp_defense 0
speed 0
type1 0
type2 384
weight_kg 20
generation 0
is_legendary 0

In [10]:
df["type2"].unique()

array(['poison', nan, 'flying', 'dark', 'electric', 'ice', 'ground',
       'fairy', 'grass', 'fighting', 'psychic', 'steel', 'fire', 'rock',
       'water', 'dragon', 'ghost', 'bug', 'normal'], dtype=object)

In [20]:
def moyenne(column):
    column = column.fillna(column.mean())
    return column

df['percentage_male'] = moyenne(df['percentage_male'])
print(df['percentage_male'])

0      88.100000
1      88.100000
2      88.100000
3      88.100000
4      88.100000
         ...
796    55.155761
797    55.155761
798    55.155761
799    55.155761
800    55.155761
Name: percentage_male, Length: 801, dtype: float64

In [12]:
#Fronction supprime les colonnes
def dropby(dataframe,name):
    dataframe = dataframe.drop([col for col in df.columns if name in col],axis=1,inplace=True)
    return dataframe

dropby(df , 'Unnamed')

df

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,Allez au boulot ! :),1.0,1.0,hello,NaN,None,0.5,2.0,2.0,1.0,...,88.100000,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,hello,0.5,0.5,2.0,2.0,1.0,...,88.100000,2,80,80,60,grass,poison,13.0,1,0
2,ù*ùfsfsf///,1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.100000,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.100000,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,NaN,1.0,1.0,0.5,ù*ùfsfsf///,0.5,1.0,1.0,...,88.100000,5,80,65,80,fire,NaN,19.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,ù*ùfsfsf///,0.5,1.0,...,55.155761,797,107,101,61,steel,flying,999.9,7,1
797,['Beast Boost'],1.0,1.0,hello,hello,0.5,2.0,4.0,1.0,hello,...,55.155761,798,59,31,109,grass,steel,0.1,7,1
798,ù*ùfsfsf///,2.0,0.5,2.0,0.5,NaN,2.0,0.5,1.0,0.5,...,55.155761,799,97,53,43,dark,dragon,888.0,7,1
799,['Prism Armor'],2.0,2.0,1.0,1.0,NaN,0.5,1.0,NaN,hello,...,55.155761,800,127,89,79,psychic,NaN,230.0,7,1
800,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,55.155761,801,130,115,65,steel,fairy,80.5,7,1

In [13]:
#Classer les differents types d'attaques
cat1 = df[(df["sp_attack"]>0) & (df["sp_attack"]<=50)]
cat2 = df[(df["sp_attack"]>50) & (df["sp_attack"]<=100)]
cat3 = df[df["sp_attack"]>101]
cat1.sort_values(by='sp_attack', ascending=True).loc[:,["name","generation", "sp_attack"]]

          name  generation  sp_attack
212    Shuckle           2         10
348     Feebas           3         10
26   Sandshrew           1         10
437     Bonsly           4         10
439    Happiny           4         15
..         ...         ...        ...
290    Ninjask           3         50
282    Surskit           3         50
702    Carbink           6         50
268     Dustox           3         50
6     Squirtle           1         50

[253 rows x 3 columns]

In [119]:
# prend en argument le dataframe, le nom de la colonne concerné et le contenu qu'on veux remplacer
#faire la fonction moyenne avant celle-ci est préconisé
def replaceBy(dfs , name , fill):
    test = df.loc[:,[col for col in df.columns if name in col]]
    test =test.loc[:,[col for col in dfs.columns if name in col]].fillna(fill)
    lst = ['ù*ùfsfsf///','hello','None', 'Allez au boulot ! :)']
    for i in range(len(lst)) :
        test = test.replace(to_replace =lst[i], 
                     value = fill) 

    df.loc[:,[col for col in df.columns if name in col]] = test
    return  df.loc[:,[col for col in df.columns if name in col]]

replaceBy(df , 'against' , '0.0')#on peut remplacer pas ce que l'ont veut 0.0 ici mais aussi par unknown par exemple
df

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary,notLegendary
0,Unknown,1.0,1.0,0.0,0.0,0.0,0.5,2.0,2.0,1.0,...,1,65,65,45,grass,poison,6.9,1,0,1
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.0,0.5,0.5,2.0,2.0,1.0,...,2,80,80,60,grass,poison,13.0,1,0,1
2,Unknown,1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,3,122,120,80,grass,poison,100.0,1,0,1
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,4,60,50,65,fire,None,8.5,1,0,1
4,"['Blaze', 'Solar Power']",0.5,0.0,1.0,1.0,0.5,0.0,0.5,1.0,1.0,...,5,80,65,80,fire,None,19.0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,0.0,0.5,1.0,...,797,107,101,61,steel,flying,999.9,7,1,0
797,['Beast Boost'],1.0,1.0,0.0,0.0,0.5,2.0,4.0,1.0,0.0,...,798,59,31,109,grass,steel,0.1,7,1,0
798,Unknown,2.0,0.5,2.0,0.5,0.0,2.0,0.5,1.0,0.5,...,799,97,53,43,dark,dragon,888.0,7,1,0
799,['Prism Armor'],2.0,2.0,1.0,1.0,0.0,0.5,1.0,0.0,0.0,...,800,127,89,79,psychic,None,230.0,7,1,0
800,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,801,130,115,65,steel,fairy,80.5,7,1,0

In [18]:
replaceBy(df , 'type' , 'None')
replaceBy(df , 'abilities' , 'Unknown')
df

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,Unknown,1.0,1.0,0.0,0.0,0.0,0.5,2.0,2.0,1.0,...,88.100000,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.0,0.5,0.5,2.0,2.0,1.0,...,88.100000,2,80,80,60,grass,poison,13.0,1,0
2,Unknown,1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.100000,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.100000,4,60,50,65,fire,None,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,0.0,1.0,1.0,0.5,0.0,0.5,1.0,1.0,...,88.100000,5,80,65,80,fire,None,19.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,0.0,0.5,1.0,...,55.155761,797,107,101,61,steel,flying,999.9,7,1
797,['Beast Boost'],1.0,1.0,0.0,0.0,0.5,2.0,4.0,1.0,0.0,...,55.155761,798,59,31,109,grass,steel,0.1,7,1
798,Unknown,2.0,0.5,2.0,0.5,0.0,2.0,0.5,1.0,0.5,...,55.155761,799,97,53,43,dark,dragon,888.0,7,1
799,['Prism Armor'],2.0,2.0,1.0,1.0,0.0,0.5,1.0,0.0,0.0,...,55.155761,800,127,89,79,psychic,None,230.0,7,1
800,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,55.155761,801,130,115,65,steel,fairy,80.5,7,1

In [23]:
import numpy as np
df['notLegendary'] = np.where(df['is_legendary'] == 0, '1', '0')
df.loc[:,('notLegendary')]

0      1
1      1
2      1
3      1
4      1
      ..
796    0
797    0
798    0
799    0
800    0
Name: notLegendary, Length: 801, dtype: object

In [114]:
# df.groupby(by=["type1"]).count()
dfspark.groupBy("type1").count().show()

+--------+-----+
|   type1|count|
+--------+-----+
|     bug|   72|
|  normal|  105|
|   ghost|   27|
|   grass|   78|
|   steel|   24|
|     ice|   23|
|   water|  114|
|  ground|   32|
|  flying|    3|
|   fairy|   18|
|    dark|   29|
|fighting|   28|
|  dragon|   27|
|  poison|   32|
| psychic|   53|
|    rock|   45|
|electric|   39|
|    fire|   52|
+--------+-----+

In [116]:
# df.groupby(by=["generation"]).count()
dfspark.groupBy("generation").count().collect()

[Row(generation='7', count=80),
 Row(generation='3', count=135),
 Row(generation='5', count=156),
 Row(generation='6', count=72),
 Row(generation='1', count=151),
 Row(generation='4', count=107),
 Row(generation='2', count=100)]